blank_issues_enabled: true
contact_links:
  - name: Questions, Ideas, Discussions
    url: https://github.com/JapiRest/docs.japi.rest/discussions
    about: Ask and answer questions, and propose new features.
